export const plantList = [
	{
		name: 'monstera',
		category: 'classique',
		id: '1ed',
		isBestSale: true,
		isSpecialOffer: false,
		water: 2,
		light: 3,
		price: 15,
	},
	{
		name: 'ficus lyrata',
		category: 'classique',
		id: '2ab',
		isBestSale: false,
		isSpecialOffer: false,
		water: 3,
		light: 1,
		price: 24
	},
	{
		name: 'pothos argenté',
		category: 'classique',
		id: '3sd',
		isBestSale: false,
		isSpecialOffer: true,
		water: 1,
		light: 3,
		price: 12,
	},
	{
		name: 'yucca',
		category: 'classique',
		id: '4kk',
		isBestSale: false,
		isSpecialOffer: true,
		water: 3,
		light: 2,
		price: 11,
	},
	{
		name: 'olivier',
		category: 'extérieur',
		id: '5pl',
		isBestSale: true,
		isSpecialOffer: true,
		water: 2,
		light: 3,
		price: 17,
	},
	{
		name: 'géranium',
		category: 'extérieur',
		id: '6uo',
		isBestSale: false,
		isSpecialOffer: false,
		water: 1,
		light: 1,
		price: 29,
	},
	{
		name: 'basilique',
		category: 'extérieur',
		id: '7ie',
		isBestSale: true,
		isSpecialOffer: false,
		water: 1,
		light: 2,
		price: 19,
	},
	{
		name: 'aloe',
		category: 'plante grasse',
		id: '8fp',
		isBestSale: true,
		isSpecialOffer: false,
		water: 3,
		light: 3,
		price: 18,
	},
	{
		name: 'succulente',
		category: 'plante grasse',
		id: '9vn',
		isBestSale: false,
		isSpecialOffer: true,
		water: 1,
		light: 3,
		price: 24,
	}
]